version: '3.4'

services:
  ms-sql-server:
    container_name: ms-sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SL!database1982"
      MSSQL_PID: Express
    ports:
      - "1982:1433"
  sl-backend:
    container_name: sl-backend
    build: .
    ports:
      - "8921:8921"
    depends_on:
      - ms-sql-server

